unit NexoPago.Entities;

interface

uses
  MVCFramework.ActiveRecord,
  MVCFramework.Serializer.Commons,
  MVCFramework.Nullables;

type
  [MVCNameCase(ncCamelCase)]
  [MVCTable('USUARIO')]
  TUsuario = class(TMVCActiveRecord)
  private
    [MVCTableField('USUARIO_ID', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt64;
    [MVCTableField('NOMBRE_USUARIO')]
    fNombreUsuario: String;
    [MVCTableField('NOMBRE')]
    fNombre: String;
    [MVCTableField('APELLIDO')]
    fApellido: NullableString;
    [MVCTableField('CORREO_ELECTRONICO')]
    fCorreoElectronico: NullableString;
    [MVCTableField('CONTRASENA_HASH')]
    [MVCDoNotSerialize]
    fContrasenaHash: String;
    [MVCTableField('ACTIVO')]
    fActivo: Boolean;
    [MVCTableField('FECHA_ULTIMO_ACCESO')]
    fFechaUltimoAcceso: NullableTDateTime;
    [MVCTableField('USUARIO_CREO_ID')]
    fUsuarioCreoID: NullableInt64;
    [MVCTableField('FECHA_CREACION', [foReadOnly])]
    fFechaCreacion: TDateTime;
    [MVCTableField('USUARIO_MODIFICO_ID')]
    fUsuarioModificoID: NullableInt64;
    [MVCTableField('FECHA_MODIFICACION')]
    fFechaModificacion: NullableTDateTime;
    [MVCTableField('ESTADO_REGISTRO')]
    fEstadoRegistro: String;
  public
    property ID: NullableInt64 read fID write fID;
    property NombreUsuario: String read fNombreUsuario write fNombreUsuario;
    property Nombre: String read fNombre write fNombre;
    property Apellido: NullableString read fApellido write fApellido;
    property CorreoElectronico: NullableString read fCorreoElectronico write fCorreoElectronico;
    property ContrasenaHash: String read fContrasenaHash write fContrasenaHash;
    property Activo: Boolean read fActivo write fActivo;
    property FechaUltimoAcceso: NullableTDateTime read fFechaUltimoAcceso write fFechaUltimoAcceso;
    property UsuarioCreoID: NullableInt64 read fUsuarioCreoID write fUsuarioCreoID;
    property FechaCreacion: TDateTime read fFechaCreacion;
    property UsuarioModificoID: NullableInt64 read fUsuarioModificoID write fUsuarioModificoID;
    property FechaModificacion: NullableTDateTime read fFechaModificacion write fFechaModificacion;
    property EstadoRegistro: String read fEstadoRegistro write fEstadoRegistro;
  end;

  [MVCNameCase(ncCamelCase)]
  [MVCTable('PROVEEDOR')]
  TProveedor = class(TMVCActiveRecord)
  private
    [MVCTableField('PROVEEDOR_ID', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt64;
    [MVCTableField('NIT')]
    fNit: String;
    [MVCTableField('CODIGO_HELISA')]
    fCodigoHelisa: NullableInt32;
    [MVCTableField('CODIGO_INTERNO')]
    fCodigoInterno: NullableString;
    [MVCTableField('NOMBRE')]
    fNombre: String;
    [MVCTableField('DIRECCION')]
    fDireccion: NullableString;
    [MVCTableField('TELEFONO')]
    fTelefono: NullableString;
    [MVCTableField('CORREO_ELECTRONICO')]
    fCorreoElectronico: NullableString;
    [MVCTableField('ACTIVO')]
    fActivo: Boolean;
    [MVCTableField('USUARIO_CREO_ID')]
    fUsuarioCreoID: NullableInt64;
    [MVCTableField('FECHA_CREACION', [foReadOnly])]
    fFechaCreacion: TDateTime;
    [MVCTableField('USUARIO_MODIFICO_ID')]
    fUsuarioModificoID: NullableInt64;
    [MVCTableField('FECHA_MODIFICACION')]
    fFechaModificacion: NullableTDateTime;
    [MVCTableField('ESTADO_REGISTRO')]
    fEstadoRegistro: String;
  public
    property ID: NullableInt64 read fID write fID;
    property Nit: String read fNit write fNit;
    property CodigoHelisa: NullableInt32 read fCodigoHelisa write fCodigoHelisa;
    property CodigoInterno: NullableString read fCodigoInterno write fCodigoInterno;
    property Nombre: String read fNombre write fNombre;
    property Direccion: NullableString read fDireccion write fDireccion;
    property Telefono: NullableString read fTelefono write fTelefono;
    property CorreoElectronico: NullableString read fCorreoElectronico write fCorreoElectronico;
    property Activo: Boolean read fActivo write fActivo;
    property UsuarioCreoID: NullableInt64 read fUsuarioCreoID write fUsuarioCreoID;
    property FechaCreacion: TDateTime read fFechaCreacion;
    property UsuarioModificoID: NullableInt64 read fUsuarioModificoID write fUsuarioModificoID;
    property FechaModificacion: NullableTDateTime read fFechaModificacion write fFechaModificacion;
    property EstadoRegistro: String read fEstadoRegistro write fEstadoRegistro;
  end;

  [MVCNameCase(ncCamelCase)]
  [MVCTable('PRODUCTO')]
  TProducto = class(TMVCActiveRecord)
  private
    [MVCTableField('PRODUCTO_ID', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt64;
    [MVCTableField('CODIGO_HELISA')]
    fCodigoHelisa: String;
    [MVCTableField('SUB_CODIGO_HELISA')]
    fSubCodigoHelisa: String;
    [MVCTableField('CODIGO_INTERNO')]
    fCodigoInterno: NullableString;
    [MVCTableField('DESCRIPCION')]
    fDescripcion: String;
    [MVCTableField('UNIDAD_MEDIDA')]
    fUnidadMedida: NullableString;
    [MVCTableField('PRECIO_REFERENCIA')]
    fPrecioReferencia: NullableCurrency;
    [MVCTableField('ACTIVO')]
    fActivo: Boolean;
    [MVCTableField('USUARIO_CREO_ID')]
    fUsuarioCreoID: NullableInt64;
    [MVCTableField('FECHA_CREACION', [foReadOnly])]
    fFechaCreacion: TDateTime;
    [MVCTableField('USUARIO_MODIFICO_ID')]
    fUsuarioModificoID: NullableInt64;
    [MVCTableField('FECHA_MODIFICACION')]
    fFechaModificacion: NullableTDateTime;
    [MVCTableField('ESTADO_REGISTRO')]
    fEstadoRegistro: String;
  public
    property ID: NullableInt64 read fID write fID;
    property CodigoHelisa: String read fCodigoHelisa write fCodigoHelisa;
    property SubCodigoHelisa: String read fSubCodigoHelisa write fSubCodigoHelisa;
    property CodigoInterno: NullableString read fCodigoInterno write fCodigoInterno;
    property Descripcion: String read fDescripcion write fDescripcion;
    property UnidadMedida: NullableString read fUnidadMedida write fUnidadMedida;
    property PrecioReferencia: NullableCurrency read fPrecioReferencia write fPrecioReferencia;
    property Activo: Boolean read fActivo write fActivo;
    property UsuarioCreoID: NullableInt64 read fUsuarioCreoID write fUsuarioCreoID;
    property FechaCreacion: TDateTime read fFechaCreacion;
    property UsuarioModificoID: NullableInt64 read fUsuarioModificoID write fUsuarioModificoID;
    property FechaModificacion: NullableTDateTime read fFechaModificacion write fFechaModificacion;
    property EstadoRegistro: String read fEstadoRegistro write fEstadoRegistro;
  end;

implementation

end.
