unit NexoPago.Entities;

interface

uses
  System.Generics.Collections,
  MVCFramework.ActiveRecord,
  MVCFramework.Serializer.Commons,
  MVCFramework.Nullables;

type
  [MVCNameCase(ncCamelCase)]
  [MVCTable('USUARIO')]
  TUsuario = class(TMVCActiveRecord)
  private
    [MVCTableField('USUARIO_ID', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt64;
    [MVCTableField('NOMBRE_USUARIO')]
    fNombreUsuario: String;
    [MVCTableField('NOMBRE')]
    fNombre: String;
    [MVCTableField('APELLIDO')]
    fApellido: NullableString;
    [MVCTableField('CORREO_ELECTRONICO')]
    fCorreoElectronico: NullableString;
    [MVCTableField('CONTRASENA_HASH')]
    [MVCDoNotSerialize]
    fContrasenaHash: String;
    [MVCTableField('ACTIVO')]
    fActivo: Boolean;
    [MVCTableField('FECHA_ULTIMO_ACCESO')]
    fFechaUltimoAcceso: NullableTDateTime;
    [MVCTableField('USUARIO_CREO_ID')]
    fUsuarioCreoID: NullableInt64;
    [MVCTableField('FECHA_CREACION', [foReadOnly])]
    fFechaCreacion: TDateTime;
    [MVCTableField('USUARIO_MODIFICO_ID')]
    fUsuarioModificoID: NullableInt64;
    [MVCTableField('FECHA_MODIFICACION')]
    fFechaModificacion: NullableTDateTime;
    [MVCTableField('ESTADO_REGISTRO')]
    fEstadoRegistro: String;
  public
    property ID: NullableInt64 read fID write fID;
    property NombreUsuario: String read fNombreUsuario write fNombreUsuario;
    property Nombre: String read fNombre write fNombre;
    property Apellido: NullableString read fApellido write fApellido;
    property CorreoElectronico: NullableString read fCorreoElectronico write fCorreoElectronico;
    property ContrasenaHash: String read fContrasenaHash write fContrasenaHash;
    property Activo: Boolean read fActivo write fActivo;
    property FechaUltimoAcceso: NullableTDateTime read fFechaUltimoAcceso write fFechaUltimoAcceso;
    property UsuarioCreoID: NullableInt64 read fUsuarioCreoID write fUsuarioCreoID;
    property FechaCreacion: TDateTime read fFechaCreacion;
    property UsuarioModificoID: NullableInt64 read fUsuarioModificoID write fUsuarioModificoID;
    property FechaModificacion: NullableTDateTime read fFechaModificacion write fFechaModificacion;
    property EstadoRegistro: String read fEstadoRegistro write fEstadoRegistro;
  end;

  [MVCNameCase(ncCamelCase)]
  [MVCTable('PROVEEDOR')]
  TProveedor = class(TMVCActiveRecord)
  private
    [MVCTableField('PROVEEDOR_ID', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt64;
    [MVCTableField('NIT')]
    fNit: String;
    [MVCTableField('CODIGO_HELISA')]
    fCodigoHelisa: NullableInt32;
    [MVCTableField('CODIGO_INTERNO')]
    fCodigoInterno: NullableString;
    [MVCTableField('NOMBRE')]
    fNombre: String;
    [MVCTableField('DIRECCION')]
    fDireccion: NullableString;
    [MVCTableField('TELEFONO')]
    fTelefono: NullableString;
    [MVCTableField('CORREO_ELECTRONICO')]
    fCorreoElectronico: NullableString;
    [MVCTableField('ACTIVO')]
    fActivo: Boolean;
    [MVCTableField('USUARIO_CREO_ID')]
    fUsuarioCreoID: NullableInt64;
    [MVCTableField('FECHA_CREACION', [foReadOnly])]
    fFechaCreacion: TDateTime;
    [MVCTableField('USUARIO_MODIFICO_ID')]
    fUsuarioModificoID: NullableInt64;
    [MVCTableField('FECHA_MODIFICACION')]
    fFechaModificacion: NullableTDateTime;
    [MVCTableField('ESTADO_REGISTRO')]
    fEstadoRegistro: String;
  public
    property ID: NullableInt64 read fID write fID;
    property Nit: String read fNit write fNit;
    property CodigoHelisa: NullableInt32 read fCodigoHelisa write fCodigoHelisa;
    property CodigoInterno: NullableString read fCodigoInterno write fCodigoInterno;
    property Nombre: String read fNombre write fNombre;
    property Direccion: NullableString read fDireccion write fDireccion;
    property Telefono: NullableString read fTelefono write fTelefono;
    property CorreoElectronico: NullableString read fCorreoElectronico write fCorreoElectronico;
    property Activo: Boolean read fActivo write fActivo;
    property UsuarioCreoID: NullableInt64 read fUsuarioCreoID write fUsuarioCreoID;
    property FechaCreacion: TDateTime read fFechaCreacion;
    property UsuarioModificoID: NullableInt64 read fUsuarioModificoID write fUsuarioModificoID;
    property FechaModificacion: NullableTDateTime read fFechaModificacion write fFechaModificacion;
    property EstadoRegistro: String read fEstadoRegistro write fEstadoRegistro;
  end;

  [MVCNameCase(ncCamelCase)]
  [MVCTable('PRODUCTO')]
  TProducto = class(TMVCActiveRecord)
  private
    [MVCTableField('PRODUCTO_ID', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt64;
    [MVCTableField('CODIGO_HELISA')]
    fCodigoHelisa: String;
    [MVCTableField('SUB_CODIGO_HELISA')]
    fSubCodigoHelisa: String;
    [MVCTableField('CODIGO_INTERNO')]
    fCodigoInterno: NullableString;
    [MVCTableField('DESCRIPCION')]
    fDescripcion: String;
    [MVCTableField('UNIDAD_MEDIDA')]
    fUnidadMedida: NullableString;
    [MVCTableField('PRECIO_REFERENCIA')]
    fPrecioReferencia: NullableCurrency;
    [MVCTableField('ACTIVO')]
    fActivo: Boolean;
    [MVCTableField('USUARIO_CREO_ID')]
    fUsuarioCreoID: NullableInt64;
    [MVCTableField('FECHA_CREACION', [foReadOnly])]
    fFechaCreacion: TDateTime;
    [MVCTableField('USUARIO_MODIFICO_ID')]
    fUsuarioModificoID: NullableInt64;
    [MVCTableField('FECHA_MODIFICACION')]
    fFechaModificacion: NullableTDateTime;
    [MVCTableField('ESTADO_REGISTRO')]
    fEstadoRegistro: String;
  public
    property ID: NullableInt64 read fID write fID;
    property CodigoHelisa: String read fCodigoHelisa write fCodigoHelisa;
    property SubCodigoHelisa: String read fSubCodigoHelisa write fSubCodigoHelisa;
    property CodigoInterno: NullableString read fCodigoInterno write fCodigoInterno;
    property Descripcion: String read fDescripcion write fDescripcion;
    property UnidadMedida: NullableString read fUnidadMedida write fUnidadMedida;
    property PrecioReferencia: NullableCurrency read fPrecioReferencia write fPrecioReferencia;
    property Activo: Boolean read fActivo write fActivo;
    property UsuarioCreoID: NullableInt64 read fUsuarioCreoID write fUsuarioCreoID;
    property FechaCreacion: TDateTime read fFechaCreacion;
    property UsuarioModificoID: NullableInt64 read fUsuarioModificoID write fUsuarioModificoID;
    property FechaModificacion: NullableTDateTime read fFechaModificacion write fFechaModificacion;
    property EstadoRegistro: String read fEstadoRegistro write fEstadoRegistro;
  end;

  [MVCNameCase(ncCamelCase)]
  [MVCTable('ORDEN_COMPRA_DETALLE')]
  TOrdenCompraDetalle = class(TMVCActiveRecord)
  private
    // ORDEN_COMPRA_DETALLE ya tiene un trigger BEFORE INSERT que asigna
    // DETALLE_ID desde SEQ_ORDEN_COMPRA_DETALLE cuando llega NULL, igual que
    // la columna IDENTITY. No hace falta (y de hecho rompe el INSERT, ver
    // historial de este archivo) pasar el nombre del generador aqui: mismo
    // patron simple que USUARIO/PROVEEDOR/PRODUCTO.
    [MVCTableField('DETALLE_ID', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt64;
    [MVCTableField('ORDEN_ID')]
    fOrdenID: Int64;
    [MVCTableField('PRODUCTO_ID')]
    fProductoID: Int64;
    [MVCTableField('CANTIDAD')]
    fCantidad: Currency;
    [MVCTableField('PRECIO_UNITARIO')]
    fPrecioUnitario: Currency;
    // Calculado por Firebird (COMPUTED BY CANTIDAD * PRECIO_UNITARIO). Jamas
    // se inserta/actualiza desde Delphi (foReadOnly). NOTA: probamos
    // foAutoGenerated para releer el valor tras el INSERT (como con una PK),
    // pero rompe el INSERT: genera un RETURNING que el framework ejecuta con
    // .Execute en vez de .Open ("Cannot execute command returning result
    // sets"). No hace falta el valor fresco justo despues de crear la orden
    // (el POST no devuelve el detalle), asi que basta con foReadOnly.
    [MVCTableField('SUBTOTAL', [foReadOnly])]
    fSubtotal: Currency;
    // Consecutivo de PETRXXXX (linea del pedido de Helisa) del que salio esta
    // cantidad. Nullable: lineas de una orden que no viene de un pedido de
    // Helisa (o creadas antes de esta funcionalidad) no lo tienen. El numero
    // de pedido en si vive en ORDEN_COMPRA.NUMERO_PEDIDO_HELISA (cabecera).
    [MVCTableField('CONSECUTIVO_PEDIDO_HELISA')]
    fConsecutivoPedidoHelisa: NullableInt32;
    [MVCTableField('USUARIO_CREO_ID')]
    fUsuarioCreoID: NullableInt64;
    [MVCTableField('FECHA_CREACION', [foReadOnly])]
    fFechaCreacion: TDateTime;
    [MVCTableField('USUARIO_MODIFICO_ID')]
    fUsuarioModificoID: NullableInt64;
    [MVCTableField('FECHA_MODIFICACION')]
    fFechaModificacion: NullableTDateTime;
    [MVCTableField('ESTADO_REGISTRO')]
    fEstadoRegistro: String;
  public
    property ID: NullableInt64 read fID write fID;
    property OrdenID: Int64 read fOrdenID write fOrdenID;
    property ProductoID: Int64 read fProductoID write fProductoID;
    property Cantidad: Currency read fCantidad write fCantidad;
    property PrecioUnitario: Currency read fPrecioUnitario write fPrecioUnitario;
    property Subtotal: Currency read fSubtotal;
    property ConsecutivoPedidoHelisa: NullableInt32 read fConsecutivoPedidoHelisa write fConsecutivoPedidoHelisa;
    property UsuarioCreoID: NullableInt64 read fUsuarioCreoID write fUsuarioCreoID;
    property FechaCreacion: TDateTime read fFechaCreacion;
    property UsuarioModificoID: NullableInt64 read fUsuarioModificoID write fUsuarioModificoID;
    property FechaModificacion: NullableTDateTime read fFechaModificacion write fFechaModificacion;
    property EstadoRegistro: String read fEstadoRegistro write fEstadoRegistro;
  end;

  [MVCNameCase(ncCamelCase)]
  [MVCTable('ORDEN_COMPRA')]
  TOrdenCompra = class(TMVCActiveRecord)
  private
    [MVCTableField('ORDEN_ID', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt64;
    [MVCTableField('MODULO_ID')]
    fModuloID: Integer;
    [MVCTableField('NUMERO_ORDEN')]
    fNumeroOrden: String;
    [MVCTableField('FECHA_ORDEN')]
    fFechaOrden: TDate;
    [MVCTableField('PROVEEDOR_ID')]
    fProveedorID: Int64;
    [MVCTableField('NUMERO_PEDIDO_HELISA')]
    fNumeroPedidoHelisa: NullableString;
    [MVCTableField('FECHA_PEDIDO_HELISA')]
    fFechaPedidoHelisa: NullableTDate;
    [MVCTableField('TOTAL_PEDIDO_HELISA')]
    fTotalPedidoHelisa: NullableCurrency;
    // Proyecto/unidad de negocio (texto libre) y solicitud (identificador
    // abreviado, ej. REM-14869, ST-004825) que origina la orden. Nullable:
    // ordenes creadas antes de este cambio no lo tienen. Ver
    // nexopago_db_alter_proyecto_solicitud.sql.
    [MVCTableField('PROYECTO')]
    fProyecto: NullableString;
    [MVCTableField('SOLICITUD')]
    fSolicitud: NullableString;
    [MVCTableField('OBSERVACIONES')]
    fObservaciones: NullableString;
    [MVCTableField('ESTADO')]
    fEstado: String;
    [MVCTableField('USUARIO_CREO_ID')]
    fUsuarioCreoID: NullableInt64;
    [MVCTableField('FECHA_CREACION', [foReadOnly])]
    fFechaCreacion: TDateTime;
    [MVCTableField('USUARIO_MODIFICO_ID')]
    fUsuarioModificoID: NullableInt64;
    [MVCTableField('FECHA_MODIFICACION')]
    fFechaModificacion: NullableTDateTime;
    [MVCTableField('ESTADO_REGISTRO')]
    fEstadoRegistro: String;
    // Lineas de detalle: se cargan solo para lectura (GetByPK/detalle), NO se
    // insertan en cascada desde aqui. La creacion de la orden orquesta
    // cabecera + lineas explicitamente en el Service, dentro de una
    // transaccion FireDAC manual (ver NexoPago.Services.Ordenes).
    [MVCOwned]
    fDetalles: TObjectList<TOrdenCompraDetalle>;
  protected
    procedure OnAfterLoad; override;
  public
    constructor Create; override;
    destructor Destroy; override;
    property ID: NullableInt64 read fID write fID;
    property ModuloID: Integer read fModuloID write fModuloID;
    property NumeroOrden: String read fNumeroOrden write fNumeroOrden;
    property FechaOrden: TDate read fFechaOrden write fFechaOrden;
    property ProveedorID: Int64 read fProveedorID write fProveedorID;
    property NumeroPedidoHelisa: NullableString read fNumeroPedidoHelisa write fNumeroPedidoHelisa;
    property FechaPedidoHelisa: NullableTDate read fFechaPedidoHelisa write fFechaPedidoHelisa;
    property TotalPedidoHelisa: NullableCurrency read fTotalPedidoHelisa write fTotalPedidoHelisa;
    property Proyecto: NullableString read fProyecto write fProyecto;
    property Solicitud: NullableString read fSolicitud write fSolicitud;
    property Observaciones: NullableString read fObservaciones write fObservaciones;
    property Estado: String read fEstado write fEstado;
    property UsuarioCreoID: NullableInt64 read fUsuarioCreoID write fUsuarioCreoID;
    property FechaCreacion: TDateTime read fFechaCreacion;
    property UsuarioModificoID: NullableInt64 read fUsuarioModificoID write fUsuarioModificoID;
    property FechaModificacion: NullableTDateTime read fFechaModificacion write fFechaModificacion;
    property EstadoRegistro: String read fEstadoRegistro write fEstadoRegistro;
    property Detalles: TObjectList<TOrdenCompraDetalle> read fDetalles;
  end;

  [MVCNameCase(ncCamelCase)]
  [MVCTable('RECIBO_CAJA_CHIPIS')]
  TReciboCajaChipis = class(TMVCActiveRecord)
  private
    [MVCTableField('RECIBO_ID', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt64;
    [MVCTableField('MODULO_ID')]
    fModuloID: Integer;
    [MVCTableField('NUMERO_RECIBO')]
    fNumeroRecibo: String;
    [MVCTableField('FECHA_RECIBO')]
    fFechaRecibo: TDate;
    [MVCTableField('ORDEN_ID')]
    fOrdenID: Int64;
    [MVCTableField('MONTO')]
    fMonto: Currency;
    [MVCTableField('TIPO_PAGO')]
    fTipoPago: String;
    [MVCTableField('ESTADO')]
    fEstado: String;
    [MVCTableField('OBSERVACIONES')]
    fObservaciones: NullableString;
    [MVCTableField('USUARIO_CREO_ID')]
    fUsuarioCreoID: NullableInt64;
    [MVCTableField('FECHA_CREACION', [foReadOnly])]
    fFechaCreacion: TDateTime;
    [MVCTableField('USUARIO_MODIFICO_ID')]
    fUsuarioModificoID: NullableInt64;
    [MVCTableField('FECHA_MODIFICACION')]
    fFechaModificacion: NullableTDateTime;
    [MVCTableField('ESTADO_REGISTRO')]
    fEstadoRegistro: String;
  public
    property ID: NullableInt64 read fID write fID;
    property ModuloID: Integer read fModuloID write fModuloID;
    property NumeroRecibo: String read fNumeroRecibo write fNumeroRecibo;
    property FechaRecibo: TDate read fFechaRecibo write fFechaRecibo;
    property OrdenID: Int64 read fOrdenID write fOrdenID;
    property Monto: Currency read fMonto write fMonto;
    property TipoPago: String read fTipoPago write fTipoPago;
    property Estado: String read fEstado write fEstado;
    property Observaciones: NullableString read fObservaciones write fObservaciones;
    property UsuarioCreoID: NullableInt64 read fUsuarioCreoID write fUsuarioCreoID;
    property FechaCreacion: TDateTime read fFechaCreacion;
    property UsuarioModificoID: NullableInt64 read fUsuarioModificoID write fUsuarioModificoID;
    property FechaModificacion: NullableTDateTime read fFechaModificacion write fFechaModificacion;
    property EstadoRegistro: String read fEstadoRegistro write fEstadoRegistro;
  end;

  [MVCNameCase(ncCamelCase)]
  [MVCTable('ENTRADAS_MERCANCIA')]
  TEntradaMercancia = class(TMVCActiveRecord)
  private
    [MVCTableField('ENTRADA_ID', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt64;
    [MVCTableField('ORDEN_ID')]
    fOrdenID: Int64;
    [MVCTableField('NUMERO_ENTRADA_HELISA')]
    fNumeroEntradaHelisa: String;
    [MVCTableField('FECHA_ENTRADA')]
    fFechaEntrada: TDate;
    [MVCTableField('OBSERVACIONES')]
    fObservaciones: NullableString;
    [MVCTableField('USUARIO_CREO_ID')]
    fUsuarioCreoID: NullableInt64;
    [MVCTableField('FECHA_CREACION', [foReadOnly])]
    fFechaCreacion: TDateTime;
    [MVCTableField('USUARIO_MODIFICO_ID')]
    fUsuarioModificoID: NullableInt64;
    [MVCTableField('FECHA_MODIFICACION')]
    fFechaModificacion: NullableTDateTime;
    [MVCTableField('ESTADO_REGISTRO')]
    fEstadoRegistro: String;
  public
    property ID: NullableInt64 read fID write fID;
    property OrdenID: Int64 read fOrdenID write fOrdenID;
    property NumeroEntradaHelisa: String read fNumeroEntradaHelisa write fNumeroEntradaHelisa;
    property FechaEntrada: TDate read fFechaEntrada write fFechaEntrada;
    property Observaciones: NullableString read fObservaciones write fObservaciones;
    property UsuarioCreoID: NullableInt64 read fUsuarioCreoID write fUsuarioCreoID;
    property FechaCreacion: TDateTime read fFechaCreacion;
    property UsuarioModificoID: NullableInt64 read fUsuarioModificoID write fUsuarioModificoID;
    property FechaModificacion: NullableTDateTime read fFechaModificacion write fFechaModificacion;
    property EstadoRegistro: String read fEstadoRegistro write fEstadoRegistro;
  end;

  [MVCNameCase(ncCamelCase)]
  [MVCTable('MODULO')]
  TModulo = class(TMVCActiveRecord)
  private
    [MVCTableField('MODULO_ID', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt64;
    [MVCTableField('NOMBRE')]
    fNombre: String;
    [MVCTableField('DESCRIPCION')]
    fDescripcion: NullableString;
    [MVCTableField('ACTIVO')]
    fActivo: Boolean;
    [MVCTableField('USUARIO_CREO_ID')]
    fUsuarioCreoID: NullableInt64;
    [MVCTableField('FECHA_CREACION', [foReadOnly])]
    fFechaCreacion: TDateTime;
    [MVCTableField('USUARIO_MODIFICO_ID')]
    fUsuarioModificoID: NullableInt64;
    [MVCTableField('FECHA_MODIFICACION')]
    fFechaModificacion: NullableTDateTime;
    [MVCTableField('ESTADO_REGISTRO')]
    fEstadoRegistro: String;
  public
    property ID: NullableInt64 read fID write fID;
    property Nombre: String read fNombre write fNombre;
    property Descripcion: NullableString read fDescripcion write fDescripcion;
    property Activo: Boolean read fActivo write fActivo;
    property UsuarioCreoID: NullableInt64 read fUsuarioCreoID write fUsuarioCreoID;
    property FechaCreacion: TDateTime read fFechaCreacion;
    property UsuarioModificoID: NullableInt64 read fUsuarioModificoID write fUsuarioModificoID;
    property FechaModificacion: NullableTDateTime read fFechaModificacion write fFechaModificacion;
    property EstadoRegistro: String read fEstadoRegistro write fEstadoRegistro;
  end;

  [MVCNameCase(ncCamelCase)]
  [MVCTable('PERFIL')]
  TPerfil = class(TMVCActiveRecord)
  private
    [MVCTableField('PERFIL_ID', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt64;
    [MVCTableField('NOMBRE')]
    fNombre: String;
    [MVCTableField('DESCRIPCION')]
    fDescripcion: NullableString;
    [MVCTableField('USUARIO_CREO_ID')]
    fUsuarioCreoID: NullableInt64;
    [MVCTableField('FECHA_CREACION', [foReadOnly])]
    fFechaCreacion: TDateTime;
    [MVCTableField('USUARIO_MODIFICO_ID')]
    fUsuarioModificoID: NullableInt64;
    [MVCTableField('FECHA_MODIFICACION')]
    fFechaModificacion: NullableTDateTime;
    [MVCTableField('ESTADO_REGISTRO')]
    fEstadoRegistro: String;
  public
    property ID: NullableInt64 read fID write fID;
    property Nombre: String read fNombre write fNombre;
    property Descripcion: NullableString read fDescripcion write fDescripcion;
    property UsuarioCreoID: NullableInt64 read fUsuarioCreoID write fUsuarioCreoID;
    property FechaCreacion: TDateTime read fFechaCreacion;
    property UsuarioModificoID: NullableInt64 read fUsuarioModificoID write fUsuarioModificoID;
    property FechaModificacion: NullableTDateTime read fFechaModificacion write fFechaModificacion;
    property EstadoRegistro: String read fEstadoRegistro write fEstadoRegistro;
  end;

  [MVCNameCase(ncCamelCase)]
  [MVCTable('PERMISO')]
  TPermiso = class(TMVCActiveRecord)
  private
    [MVCTableField('PERMISO_ID', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt64;
    [MVCTableField('MODULO_ID')]
    fModuloID: Int64;
    [MVCTableField('ACCION')]
    fAccion: String;
    [MVCTableField('DESCRIPCION')]
    fDescripcion: NullableString;
    [MVCTableField('USUARIO_CREO_ID')]
    fUsuarioCreoID: NullableInt64;
    [MVCTableField('FECHA_CREACION', [foReadOnly])]
    fFechaCreacion: TDateTime;
    [MVCTableField('USUARIO_MODIFICO_ID')]
    fUsuarioModificoID: NullableInt64;
    [MVCTableField('FECHA_MODIFICACION')]
    fFechaModificacion: NullableTDateTime;
    [MVCTableField('ESTADO_REGISTRO')]
    fEstadoRegistro: String;
  public
    property ID: NullableInt64 read fID write fID;
    property ModuloID: Int64 read fModuloID write fModuloID;
    property Accion: String read fAccion write fAccion;
    property Descripcion: NullableString read fDescripcion write fDescripcion;
    property UsuarioCreoID: NullableInt64 read fUsuarioCreoID write fUsuarioCreoID;
    property FechaCreacion: TDateTime read fFechaCreacion;
    property UsuarioModificoID: NullableInt64 read fUsuarioModificoID write fUsuarioModificoID;
    property FechaModificacion: NullableTDateTime read fFechaModificacion write fFechaModificacion;
    property EstadoRegistro: String read fEstadoRegistro write fEstadoRegistro;
  end;

  // Empresa Helisa activa (fila unica: SINGLETON_LOCK tiene UNIQUE + CHECK a
  // nivel de BD). SINGLETON_LOCK no se mapea como propiedad publica: no
  // aporta valor al DTO, solo es un mecanismo de integridad en la tabla.
  [MVCNameCase(ncCamelCase)]
  [MVCTable('EMPRESA_ACTIVA')]
  TEmpresaActiva = class(TMVCActiveRecord)
  private
    [MVCTableField('EMPRESA_ACTIVA_ID', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt64;
    [MVCTableField('CODIGO_EMPRESA_HELISA')]
    fCodigoEmpresaHelisa: Integer;
    [MVCTableField('NOMBRE_EMPRESA')]
    fNombreEmpresa: String;
    [MVCTableField('USUARIO_CREO_ID')]
    fUsuarioCreoID: NullableInt64;
    [MVCTableField('FECHA_CREACION', [foReadOnly])]
    fFechaCreacion: TDateTime;
    [MVCTableField('USUARIO_MODIFICO_ID')]
    fUsuarioModificoID: NullableInt64;
    [MVCTableField('FECHA_MODIFICACION')]
    fFechaModificacion: NullableTDateTime;
  public
    property ID: NullableInt64 read fID write fID;
    property CodigoEmpresaHelisa: Integer read fCodigoEmpresaHelisa write fCodigoEmpresaHelisa;
    property NombreEmpresa: String read fNombreEmpresa write fNombreEmpresa;
    property UsuarioCreoID: NullableInt64 read fUsuarioCreoID write fUsuarioCreoID;
    property FechaCreacion: TDateTime read fFechaCreacion;
    property UsuarioModificoID: NullableInt64 read fUsuarioModificoID write fUsuarioModificoID;
    property FechaModificacion: NullableTDateTime read fFechaModificacion write fFechaModificacion;
  end;

  // Historial de cambios de EMPRESA_ACTIVA (auditoria, no CRUD: solo se
  // inserta, nunca se actualiza/elimina). No tiene columnas de auditoria
  // propias (USUARIO_CREO_ID/FECHA_CREACION/...): USUARIO_ID + FECHA_CAMBIO
  // ya cumplen ese rol, la fila entera ES el registro de auditoria.
  [MVCNameCase(ncCamelCase)]
  [MVCTable('EMPRESA_ACTIVA_HISTORIAL')]
  TEmpresaActivaHistorial = class(TMVCActiveRecord)
  private
    [MVCTableField('HISTORIAL_ID', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt64;
    [MVCTableField('CODIGO_EMPRESA_ANTERIOR')]
    fCodigoEmpresaAnterior: NullableInt32;
    [MVCTableField('NOMBRE_EMPRESA_ANTERIOR')]
    fNombreEmpresaAnterior: NullableString;
    [MVCTableField('CODIGO_EMPRESA_NUEVA')]
    fCodigoEmpresaNueva: Integer;
    [MVCTableField('NOMBRE_EMPRESA_NUEVA')]
    fNombreEmpresaNueva: String;
    [MVCTableField('USUARIO_ID')]
    fUsuarioID: Int64;
    [MVCTableField('FECHA_CAMBIO', [foReadOnly])]
    fFechaCambio: TDateTime;
  public
    property ID: NullableInt64 read fID write fID;
    property CodigoEmpresaAnterior: NullableInt32 read fCodigoEmpresaAnterior write fCodigoEmpresaAnterior;
    property NombreEmpresaAnterior: NullableString read fNombreEmpresaAnterior write fNombreEmpresaAnterior;
    property CodigoEmpresaNueva: Integer read fCodigoEmpresaNueva write fCodigoEmpresaNueva;
    property NombreEmpresaNueva: String read fNombreEmpresaNueva write fNombreEmpresaNueva;
    property UsuarioID: Int64 read fUsuarioID write fUsuarioID;
    property FechaCambio: TDateTime read fFechaCambio;
  end;

implementation

uses
  System.SysUtils;

constructor TOrdenCompra.Create;
begin
  inherited Create;
  fDetalles := TObjectList<TOrdenCompraDetalle>.Create(True);
end;

destructor TOrdenCompra.Destroy;
begin
  fDetalles.Free;
  inherited Destroy;
end;

procedure TOrdenCompra.OnAfterLoad;
var
  lList: TObjectList<TOrdenCompraDetalle>;
begin
  inherited;
  lList := TMVCActiveRecord.SelectRQL<TOrdenCompraDetalle>(Format('eq(ordenId,%d)', [ID.ValueOrDefault]), 1000);
  try
    fDetalles.Clear;
    fDetalles.AddRange(lList);
    lList.OwnsObjects := False;
  finally
    lList.Free;
  end;
end;

end.
