-- Alter puntual para bases NEXOPAGODB.FDB ya creadas antes de este cambio.
-- Ejecutar una sola vez contra la base real (SYSDBA). No afecta ordenes ni
-- entradas ya registradas: la tabla nueva queda vacia, no se puede
-- reconstruir retroactivamente cuanto se recibio de cada entrada anterior
-- (esa granularidad nunca se capturo). Ver nexopago_db.sql para el esquema
-- completo ya actualizado (instalaciones nuevas).
--
-- Contexto: negocio requiere que "Registrar Entrada de Mercancia" controle
-- la cantidad recibida por CADA producto de la orden (no solo un flag
-- "completa" a nivel de toda la orden), validando que nunca se reciba mas
-- de lo pedido por linea, y permitiendo calcular el % real recibido.

CREATE SEQUENCE SEQ_ENTRADA_DETALLE START WITH 0 INCREMENT BY 1;
ALTER SEQUENCE SEQ_ENTRADA_DETALLE RESTART WITH 0;

CREATE TABLE ENTRADA_DETALLE (
    DETALLE_ID           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ENTRADA_ID           INTEGER NOT NULL,
    ORDEN_DETALLE_ID     INTEGER NOT NULL,
    CANTIDAD_RECIBIDA    NUMERIC(15,4) NOT NULL,
    USUARIO_CREO_ID      INTEGER,
    FECHA_CREACION       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_MODIFICO_ID  INTEGER,
    FECHA_MODIFICACION   TIMESTAMP,
    ESTADO_REGISTRO      CHAR(1) CHARACTER SET ISO8859_1 DEFAULT 'A',
    "VERSION"            INTEGER DEFAULT 0
);

ALTER TABLE ENTRADA_DETALLE ADD PRIMARY KEY (DETALLE_ID);

ALTER TABLE ENTRADA_DETALLE ADD CONSTRAINT FK_ENTRADA_DETALLE_ENTRADA
    FOREIGN KEY (ENTRADA_ID) REFERENCES ENTRADAS_MERCANCIA (ENTRADA_ID);
ALTER TABLE ENTRADA_DETALLE ADD CONSTRAINT FK_ENTRADA_DETALLE_1
    FOREIGN KEY (ORDEN_DETALLE_ID) REFERENCES ORDEN_COMPRA_DETALLE (DETALLE_ID);
ALTER TABLE ENTRADA_DETALLE ADD CONSTRAINT FK_ENTRADA_DETALLE_2
    FOREIGN KEY (USUARIO_CREO_ID) REFERENCES USUARIO (USUARIO_ID);
ALTER TABLE ENTRADA_DETALLE ADD CONSTRAINT FK_ENTRADA_DETALLE_3
    FOREIGN KEY (USUARIO_MODIFICO_ID) REFERENCES USUARIO (USUARIO_ID);

SET TERM ^ ;

CREATE TRIGGER TR_ENTRADA_DETALLE_ID FOR ENTRADA_DETALLE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.DETALLE_ID IS NULL) THEN
        NEW.DETALLE_ID = GEN_ID(SEQ_ENTRADA_DETALLE, 1);
END ^

SET TERM ; ^

COMMENT ON TABLE ENTRADA_DETALLE IS
'Cantidad recibida por linea de ORDEN_COMPRA_DETALLE en cada entrada de mercancia (control de recepcion parcial por producto)';

COMMENT ON COLUMN ENTRADA_DETALLE.ORDEN_DETALLE_ID IS
'Linea de ORDEN_COMPRA_DETALLE a la que corresponde esta cantidad recibida';

COMMENT ON COLUMN ENTRADA_DETALLE.CANTIDAD_RECIBIDA IS
'Cantidad recibida en esta entrada para esa linea (no puede exceder el saldo pendiente de la linea)';

COMMIT;
