-- Alter puntual para bases NEXOPAGODB.FDB ya creadas antes de este cambio.
-- Ejecutar una sola vez contra la base real (SYSDBA). Ver nexopago_db.sql
-- para el esquema completo (instalaciones nuevas deberian incorporar este
-- mismo contenido alli).
--
-- Contexto: OnAuthorization (NexoPago.Services.Auth.pas) siempre devolvia
-- AIsAuthorized := True -solo habia autenticacion, no autorizacion real por
-- permiso-. Este cambio activa el atributo [TMVCRequiresPermiso(modulo, accion)]
-- sobre las acciones de los controllers, verificado via RTTI en
-- OnAuthorization contra IPermisoRepository.UsuarioTienePermiso (el mismo
-- mecanismo que ya usaba TEmpresaService.CambiarEmpresaActiva). Para que la
-- autorizacion real no rompa el acceso, este script:
--   1) Amplia PERMISO.ACCION (20 -> 40 caracteres): codigos nuevos como
--      PROVEEDORES_ELIMINAR no caben en VARCHAR(20).
--   2) Renombra los 3 permisos existentes (por PERMISO_ID, sin tocar
--      PERFIL_PERMISO) a codigos mas descriptivos por recurso.
--   3) Inserta todos los permisos granulares nuevos que exige el mapeo de
--      controllers -> [TMVCRequiresPermiso].
--   4) Asigna TODOS los permisos nuevos al perfil ADMINISTRADOR (perfil 1),
--      para que el admin no pierda acceso a nada al empezar a exigirse la
--      autorizacion de verdad. OPERADOR_COMPRA (perfil 2) NO recibe nada
--      nuevo aqui: esa asignacion se decide manualmente despues desde la
--      pantalla de Permisos.
--
-- Idempotencia: los UPDATE de renombrado son idempotentes (si ya se
-- corrieron, el segundo UPDATE no encuentra el valor viejo y no hace nada).
-- Los INSERT de permisos/asignaciones usan NOT EXISTS para poder re-correr
-- el script sin duplicar filas.

-- 1) Ampliar PERMISO.ACCION
-- El UNIQUE (MODULO_ID, ACCION) (UQ_PERMISO_MODULO_ACCION) usa un indice
-- sobre ACCION; Firebird no permite ALTER COLUMN TYPE mientras ese indice
-- exista (SQLSTATE 27000, "Cannot update index segment used by an Integrity
-- Constraint"). Se elimina antes del ALTER y se recrea despues, idéntico.
ALTER TABLE PERMISO DROP CONSTRAINT UQ_PERMISO_MODULO_ACCION;
COMMIT;

ALTER TABLE PERMISO ALTER COLUMN ACCION TYPE VARCHAR(40);
COMMIT;

ALTER TABLE PERMISO ADD CONSTRAINT UQ_PERMISO_MODULO_ACCION UNIQUE (MODULO_ID, ACCION);
COMMIT;

-- 2) Renombrar los 3 permisos existentes (por ID, PERFIL_PERMISO no se toca)
UPDATE PERMISO SET ACCION = 'ORDENES_CREAR' WHERE PERMISO_ID = 1 AND ACCION = 'CREAR';
UPDATE PERMISO SET ACCION = 'ORDENES_LEER' WHERE PERMISO_ID = 2 AND ACCION = 'LEER';
UPDATE PERMISO SET ACCION = 'USUARIOS_LEER' WHERE PERMISO_ID = 3 AND ACCION = 'LEER';
-- PERMISO_ID = 4 (CAMBIAR_EMPRESA) no cambia.
COMMIT;

-- 3) Insertar permisos nuevos que faltan
-- MODULO_ID = 1 (CHIPIS)
INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 1, 'ORDENES_EDITAR', 'Editar ordenes de compra' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 1 AND ACCION = 'ORDENES_EDITAR');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 1, 'ORDENES_ANULAR', 'Anular ordenes de compra' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 1 AND ACCION = 'ORDENES_ANULAR');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 1, 'ENTRADAS_LEER', 'Ver entradas de mercancia' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 1 AND ACCION = 'ENTRADAS_LEER');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 1, 'ENTRADAS_REGISTRAR', 'Registrar entradas de mercancia' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 1 AND ACCION = 'ENTRADAS_REGISTRAR');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 1, 'PROVEEDORES_LEER', 'Ver proveedores' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 1 AND ACCION = 'PROVEEDORES_LEER');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 1, 'PROVEEDORES_CREAR', 'Crear proveedores' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 1 AND ACCION = 'PROVEEDORES_CREAR');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 1, 'PROVEEDORES_EDITAR', 'Editar proveedores' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 1 AND ACCION = 'PROVEEDORES_EDITAR');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 1, 'PROVEEDORES_ELIMINAR', 'Eliminar proveedores' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 1 AND ACCION = 'PROVEEDORES_ELIMINAR');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 1, 'RECIBOS_LEER', 'Ver recibos de caja' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 1 AND ACCION = 'RECIBOS_LEER');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 1, 'RECIBOS_CREAR', 'Registrar recibos de caja' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 1 AND ACCION = 'RECIBOS_CREAR');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 1, 'RECIBOS_ANULAR', 'Anular recibos de caja' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 1 AND ACCION = 'RECIBOS_ANULAR');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 1, 'PRODUCTOS_LEER', 'Ver productos' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 1 AND ACCION = 'PRODUCTOS_LEER');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 1, 'PRODUCTOS_SINCRONIZAR', 'Sincronizar productos desde Helisa' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 1 AND ACCION = 'PRODUCTOS_SINCRONIZAR');

-- MODULO_ID = 2 (ADMINISTRACION)
INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 2, 'USUARIOS_CREAR', 'Crear usuarios' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 2 AND ACCION = 'USUARIOS_CREAR');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 2, 'USUARIOS_EDITAR', 'Editar usuarios' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 2 AND ACCION = 'USUARIOS_EDITAR');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 2, 'USUARIOS_ESTADO', 'Activar o inactivar usuarios' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 2 AND ACCION = 'USUARIOS_ESTADO');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 2, 'PERMISOS_LEER', 'Ver catalogos y matriz de permisos' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 2 AND ACCION = 'PERMISOS_LEER');

INSERT INTO PERMISO (MODULO_ID, ACCION, DESCRIPCION)
  SELECT 2, 'PERMISOS_ASIGNAR', 'Asignar permisos a un perfil' FROM RDB$DATABASE
  WHERE NOT EXISTS (SELECT 1 FROM PERMISO WHERE MODULO_ID = 2 AND ACCION = 'PERMISOS_ASIGNAR');

COMMIT;

-- 4) Asignar TODOS los permisos recien insertados al perfil ADMINISTRADOR (1).
-- No toca los permisos 1-4 (ya estaban asignados desde antes) ni asigna nada
-- a OPERADOR_COMPRA (2).
INSERT INTO PERFIL_PERMISO (PERFIL_ID, PERMISO_ID)
  SELECT 1, P.PERMISO_ID
  FROM PERMISO P
  WHERE P.ACCION IN (
    'ORDENES_EDITAR', 'ORDENES_ANULAR',
    'ENTRADAS_LEER', 'ENTRADAS_REGISTRAR',
    'PROVEEDORES_LEER', 'PROVEEDORES_CREAR', 'PROVEEDORES_EDITAR', 'PROVEEDORES_ELIMINAR',
    'RECIBOS_LEER', 'RECIBOS_CREAR', 'RECIBOS_ANULAR',
    'PRODUCTOS_LEER', 'PRODUCTOS_SINCRONIZAR',
    'USUARIOS_CREAR', 'USUARIOS_EDITAR', 'USUARIOS_ESTADO',
    'PERMISOS_LEER', 'PERMISOS_ASIGNAR'
  )
  AND NOT EXISTS (
    SELECT 1 FROM PERFIL_PERMISO PP
    WHERE PP.PERFIL_ID = 1 AND PP.PERMISO_ID = P.PERMISO_ID
  );

COMMIT;
